name: Go

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build

    - name: Test
      run: go test -v ./...

    - uses: actions/upload-artifact@v3
      with:
        name: HelloGo
        path: ./HelloGo

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'development'
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: HelloGo
        path: ./HelloGo
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.8.0
      with:
        local: ./HelloGo
        remote: /home/ods-cicd-user
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
